# Generated by Django 4.2.5 on 2023-09-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.JSONField()),
                ('name', models.CharField()),
                ('icon', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('has_subtitles', models.BooleanField()),
                ('is_multilingual', models.BooleanField()),
                ('is_hd', models.BooleanField()),
                ('is_uhd', models.BooleanField()),
            ],
        ),
    ]
