# Generated by Django 4.2.5 on 2023-09-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='icon',
            field=models.ImageField(upload_to='icons/'),
        ),
    ]
