# Generated by Django 4.2.5 on 2023-09-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv', '0005_alter_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
